sudo: required

language: node_js

node_js:

  - "stable"

services:
  - docker

before_install:
  - docker build -t moreno1/multi-docker1 -f ./client/Dockerfile.dev ./client

script:
  - docker run moreno1/multi-docker1 npm run test -- --coverage

after_success:
  - docker build -t moreno1/multi-client ./client
  - docker build -t moreno1/multi-nginx ./nginx
  - docker build -t moreno1/multi-server ./server
  - docker build -t moreno1/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push moreno1/multi-client
  - docker push moreno1/multi-nginx
  - docker push moreno1/multi-server
  - docker push moreno1/multi-worker
