apiVersion: v1
kind: Pod 
metadata:
  name: voting-app-pod
  labels: 
    name: voting-app-pod

spec:
  containers:
      - name: voting-app
        image: docker pull dockersamples/examplevotingapp_vote
        ports:
          - containerPod: 80
